/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SobreImport } from './routes/sobre'
import { Route as LojaImport } from './routes/loja'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedHomeImport } from './routes/_authenticated/home'
import { Route as AuthenticatedBuildingImport } from './routes/_authenticated/building'
import { Route as AuthenticatedUsuariosIndexImport } from './routes/_authenticated/usuarios/index'
import { Route as AuthenticatedTreinamentosIndexImport } from './routes/_authenticated/treinamentos/index'
import { Route as AuthenticatedInventariosIndexImport } from './routes/_authenticated/inventarios/index'
import { Route as AuthenticatedClientesIndexImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedUsuariosPerfisImport } from './routes/_authenticated/usuarios/perfis'
import { Route as AuthenticatedTreinamentosTurmasImport } from './routes/_authenticated/treinamentos/turmas'
import { Route as AuthenticatedTreinamentosProvasImport } from './routes/_authenticated/treinamentos/provas'
import { Route as AuthenticatedTreinamentosInstrutoresImport } from './routes/_authenticated/treinamentos/instrutores'
import { Route as AuthenticatedTreinamentosCursosImport } from './routes/_authenticated/treinamentos/cursos'
import { Route as AuthenticatedTreinamentosCertificadosImport } from './routes/_authenticated/treinamentos/certificados'
import { Route as AuthenticatedTreinamentosAlunosImport } from './routes/_authenticated/treinamentos/alunos'
import { Route as AuthenticatedSiteServicosImport } from './routes/_authenticated/site/servicos'
import { Route as AuthenticatedSiteProdutosImport } from './routes/_authenticated/site/produtos'
import { Route as AuthenticatedInventariosDashboardImport } from './routes/_authenticated/inventarios/dashboard'
import { Route as AuthenticatedInventariosAutorizadosImport } from './routes/_authenticated/inventarios/autorizados'
import { Route as AuthenticatedInventariosAccessControlImport } from './routes/_authenticated/inventarios/access-control'
import { Route as AuthenticatedInventariosAreasIndexImport } from './routes/_authenticated/inventarios/areas/index'
import { Route as AuthenticatedInventariosAreasAreaIdImport } from './routes/_authenticated/inventarios/areas/$areaId'

// Create/Update Routes

const SobreRoute = SobreImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRoute,
} as any)

const LojaRoute = LojaImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeRoute = AuthenticatedHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedBuildingRoute = AuthenticatedBuildingImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUsuariosIndexRoute = AuthenticatedUsuariosIndexImport.update(
  {
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedTreinamentosIndexRoute =
  AuthenticatedTreinamentosIndexImport.update({
    id: '/treinamentos/',
    path: '/treinamentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosIndexRoute =
  AuthenticatedInventariosIndexImport.update({
    id: '/inventarios/',
    path: '/inventarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedClientesIndexRoute = AuthenticatedClientesIndexImport.update(
  {
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedUsuariosPerfisRoute =
  AuthenticatedUsuariosPerfisImport.update({
    id: '/usuarios/perfis',
    path: '/usuarios/perfis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosTurmasRoute =
  AuthenticatedTreinamentosTurmasImport.update({
    id: '/treinamentos/turmas',
    path: '/treinamentos/turmas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosProvasRoute =
  AuthenticatedTreinamentosProvasImport.update({
    id: '/treinamentos/provas',
    path: '/treinamentos/provas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosInstrutoresRoute =
  AuthenticatedTreinamentosInstrutoresImport.update({
    id: '/treinamentos/instrutores',
    path: '/treinamentos/instrutores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosCursosRoute =
  AuthenticatedTreinamentosCursosImport.update({
    id: '/treinamentos/cursos',
    path: '/treinamentos/cursos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosCertificadosRoute =
  AuthenticatedTreinamentosCertificadosImport.update({
    id: '/treinamentos/certificados',
    path: '/treinamentos/certificados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosAlunosRoute =
  AuthenticatedTreinamentosAlunosImport.update({
    id: '/treinamentos/alunos',
    path: '/treinamentos/alunos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSiteServicosRoute = AuthenticatedSiteServicosImport.update({
  id: '/site/servicos',
  path: '/site/servicos',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSiteProdutosRoute = AuthenticatedSiteProdutosImport.update({
  id: '/site/produtos',
  path: '/site/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedInventariosDashboardRoute =
  AuthenticatedInventariosDashboardImport.update({
    id: '/inventarios/dashboard',
    path: '/inventarios/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAutorizadosRoute =
  AuthenticatedInventariosAutorizadosImport.update({
    id: '/inventarios/autorizados',
    path: '/inventarios/autorizados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAccessControlRoute =
  AuthenticatedInventariosAccessControlImport.update({
    id: '/inventarios/access-control',
    path: '/inventarios/access-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAreasIndexRoute =
  AuthenticatedInventariosAreasIndexImport.update({
    id: '/inventarios/areas/',
    path: '/inventarios/areas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAreasAreaIdRoute =
  AuthenticatedInventariosAreasAreaIdImport.update({
    id: '/inventarios/areas/$areaId',
    path: '/inventarios/areas/$areaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaImport
      parentRoute: typeof rootRoute
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/building': {
      id: '/_authenticated/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof AuthenticatedBuildingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/access-control': {
      id: '/_authenticated/inventarios/access-control'
      path: '/inventarios/access-control'
      fullPath: '/inventarios/access-control'
      preLoaderRoute: typeof AuthenticatedInventariosAccessControlImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/autorizados': {
      id: '/_authenticated/inventarios/autorizados'
      path: '/inventarios/autorizados'
      fullPath: '/inventarios/autorizados'
      preLoaderRoute: typeof AuthenticatedInventariosAutorizadosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/dashboard': {
      id: '/_authenticated/inventarios/dashboard'
      path: '/inventarios/dashboard'
      fullPath: '/inventarios/dashboard'
      preLoaderRoute: typeof AuthenticatedInventariosDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/site/produtos': {
      id: '/_authenticated/site/produtos'
      path: '/site/produtos'
      fullPath: '/site/produtos'
      preLoaderRoute: typeof AuthenticatedSiteProdutosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/site/servicos': {
      id: '/_authenticated/site/servicos'
      path: '/site/servicos'
      fullPath: '/site/servicos'
      preLoaderRoute: typeof AuthenticatedSiteServicosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/alunos': {
      id: '/_authenticated/treinamentos/alunos'
      path: '/treinamentos/alunos'
      fullPath: '/treinamentos/alunos'
      preLoaderRoute: typeof AuthenticatedTreinamentosAlunosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/certificados': {
      id: '/_authenticated/treinamentos/certificados'
      path: '/treinamentos/certificados'
      fullPath: '/treinamentos/certificados'
      preLoaderRoute: typeof AuthenticatedTreinamentosCertificadosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/cursos': {
      id: '/_authenticated/treinamentos/cursos'
      path: '/treinamentos/cursos'
      fullPath: '/treinamentos/cursos'
      preLoaderRoute: typeof AuthenticatedTreinamentosCursosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/instrutores': {
      id: '/_authenticated/treinamentos/instrutores'
      path: '/treinamentos/instrutores'
      fullPath: '/treinamentos/instrutores'
      preLoaderRoute: typeof AuthenticatedTreinamentosInstrutoresImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/provas': {
      id: '/_authenticated/treinamentos/provas'
      path: '/treinamentos/provas'
      fullPath: '/treinamentos/provas'
      preLoaderRoute: typeof AuthenticatedTreinamentosProvasImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/turmas': {
      id: '/_authenticated/treinamentos/turmas'
      path: '/treinamentos/turmas'
      fullPath: '/treinamentos/turmas'
      preLoaderRoute: typeof AuthenticatedTreinamentosTurmasImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/usuarios/perfis': {
      id: '/_authenticated/usuarios/perfis'
      path: '/usuarios/perfis'
      fullPath: '/usuarios/perfis'
      preLoaderRoute: typeof AuthenticatedUsuariosPerfisImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/': {
      id: '/_authenticated/inventarios/'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof AuthenticatedInventariosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/': {
      id: '/_authenticated/treinamentos/'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof AuthenticatedTreinamentosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/usuarios/': {
      id: '/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/areas/$areaId': {
      id: '/_authenticated/inventarios/areas/$areaId'
      path: '/inventarios/areas/$areaId'
      fullPath: '/inventarios/areas/$areaId'
      preLoaderRoute: typeof AuthenticatedInventariosAreasAreaIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/areas/': {
      id: '/_authenticated/inventarios/areas/'
      path: '/inventarios/areas'
      fullPath: '/inventarios/areas'
      preLoaderRoute: typeof AuthenticatedInventariosAreasIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedBuildingRoute: typeof AuthenticatedBuildingRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInventariosAccessControlRoute: typeof AuthenticatedInventariosAccessControlRoute
  AuthenticatedInventariosAutorizadosRoute: typeof AuthenticatedInventariosAutorizadosRoute
  AuthenticatedInventariosDashboardRoute: typeof AuthenticatedInventariosDashboardRoute
  AuthenticatedSiteProdutosRoute: typeof AuthenticatedSiteProdutosRoute
  AuthenticatedSiteServicosRoute: typeof AuthenticatedSiteServicosRoute
  AuthenticatedTreinamentosAlunosRoute: typeof AuthenticatedTreinamentosAlunosRoute
  AuthenticatedTreinamentosCertificadosRoute: typeof AuthenticatedTreinamentosCertificadosRoute
  AuthenticatedTreinamentosCursosRoute: typeof AuthenticatedTreinamentosCursosRoute
  AuthenticatedTreinamentosInstrutoresRoute: typeof AuthenticatedTreinamentosInstrutoresRoute
  AuthenticatedTreinamentosProvasRoute: typeof AuthenticatedTreinamentosProvasRoute
  AuthenticatedTreinamentosTurmasRoute: typeof AuthenticatedTreinamentosTurmasRoute
  AuthenticatedUsuariosPerfisRoute: typeof AuthenticatedUsuariosPerfisRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedInventariosIndexRoute: typeof AuthenticatedInventariosIndexRoute
  AuthenticatedTreinamentosIndexRoute: typeof AuthenticatedTreinamentosIndexRoute
  AuthenticatedUsuariosIndexRoute: typeof AuthenticatedUsuariosIndexRoute
  AuthenticatedInventariosAreasAreaIdRoute: typeof AuthenticatedInventariosAreasAreaIdRoute
  AuthenticatedInventariosAreasIndexRoute: typeof AuthenticatedInventariosAreasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuildingRoute: AuthenticatedBuildingRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInventariosAccessControlRoute:
    AuthenticatedInventariosAccessControlRoute,
  AuthenticatedInventariosAutorizadosRoute:
    AuthenticatedInventariosAutorizadosRoute,
  AuthenticatedInventariosDashboardRoute:
    AuthenticatedInventariosDashboardRoute,
  AuthenticatedSiteProdutosRoute: AuthenticatedSiteProdutosRoute,
  AuthenticatedSiteServicosRoute: AuthenticatedSiteServicosRoute,
  AuthenticatedTreinamentosAlunosRoute: AuthenticatedTreinamentosAlunosRoute,
  AuthenticatedTreinamentosCertificadosRoute:
    AuthenticatedTreinamentosCertificadosRoute,
  AuthenticatedTreinamentosCursosRoute: AuthenticatedTreinamentosCursosRoute,
  AuthenticatedTreinamentosInstrutoresRoute:
    AuthenticatedTreinamentosInstrutoresRoute,
  AuthenticatedTreinamentosProvasRoute: AuthenticatedTreinamentosProvasRoute,
  AuthenticatedTreinamentosTurmasRoute: AuthenticatedTreinamentosTurmasRoute,
  AuthenticatedUsuariosPerfisRoute: AuthenticatedUsuariosPerfisRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedInventariosIndexRoute: AuthenticatedInventariosIndexRoute,
  AuthenticatedTreinamentosIndexRoute: AuthenticatedTreinamentosIndexRoute,
  AuthenticatedUsuariosIndexRoute: AuthenticatedUsuariosIndexRoute,
  AuthenticatedInventariosAreasAreaIdRoute:
    AuthenticatedInventariosAreasAreaIdRoute,
  AuthenticatedInventariosAreasIndexRoute:
    AuthenticatedInventariosAreasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/sobre': typeof SobreRoute
  '/building': typeof AuthenticatedBuildingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/site/produtos': typeof AuthenticatedSiteProdutosRoute
  '/site/servicos': typeof AuthenticatedSiteServicosRoute
  '/treinamentos/alunos': typeof AuthenticatedTreinamentosAlunosRoute
  '/treinamentos/certificados': typeof AuthenticatedTreinamentosCertificadosRoute
  '/treinamentos/cursos': typeof AuthenticatedTreinamentosCursosRoute
  '/treinamentos/instrutores': typeof AuthenticatedTreinamentosInstrutoresRoute
  '/treinamentos/provas': typeof AuthenticatedTreinamentosProvasRoute
  '/treinamentos/turmas': typeof AuthenticatedTreinamentosTurmasRoute
  '/usuarios/perfis': typeof AuthenticatedUsuariosPerfisRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
  '/treinamentos': typeof AuthenticatedTreinamentosIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
  '/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/inventarios/areas': typeof AuthenticatedInventariosAreasIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/sobre': typeof SobreRoute
  '/building': typeof AuthenticatedBuildingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/site/produtos': typeof AuthenticatedSiteProdutosRoute
  '/site/servicos': typeof AuthenticatedSiteServicosRoute
  '/treinamentos/alunos': typeof AuthenticatedTreinamentosAlunosRoute
  '/treinamentos/certificados': typeof AuthenticatedTreinamentosCertificadosRoute
  '/treinamentos/cursos': typeof AuthenticatedTreinamentosCursosRoute
  '/treinamentos/instrutores': typeof AuthenticatedTreinamentosInstrutoresRoute
  '/treinamentos/provas': typeof AuthenticatedTreinamentosProvasRoute
  '/treinamentos/turmas': typeof AuthenticatedTreinamentosTurmasRoute
  '/usuarios/perfis': typeof AuthenticatedUsuariosPerfisRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
  '/treinamentos': typeof AuthenticatedTreinamentosIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
  '/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/inventarios/areas': typeof AuthenticatedInventariosAreasIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/building': typeof AuthenticatedBuildingRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/_authenticated/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/_authenticated/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/_authenticated/site/produtos': typeof AuthenticatedSiteProdutosRoute
  '/_authenticated/site/servicos': typeof AuthenticatedSiteServicosRoute
  '/_authenticated/treinamentos/alunos': typeof AuthenticatedTreinamentosAlunosRoute
  '/_authenticated/treinamentos/certificados': typeof AuthenticatedTreinamentosCertificadosRoute
  '/_authenticated/treinamentos/cursos': typeof AuthenticatedTreinamentosCursosRoute
  '/_authenticated/treinamentos/instrutores': typeof AuthenticatedTreinamentosInstrutoresRoute
  '/_authenticated/treinamentos/provas': typeof AuthenticatedTreinamentosProvasRoute
  '/_authenticated/treinamentos/turmas': typeof AuthenticatedTreinamentosTurmasRoute
  '/_authenticated/usuarios/perfis': typeof AuthenticatedUsuariosPerfisRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/inventarios/': typeof AuthenticatedInventariosIndexRoute
  '/_authenticated/treinamentos/': typeof AuthenticatedTreinamentosIndexRoute
  '/_authenticated/usuarios/': typeof AuthenticatedUsuariosIndexRoute
  '/_authenticated/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/_authenticated/inventarios/areas/': typeof AuthenticatedInventariosAreasIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/loja'
    | '/sobre'
    | '/building'
    | '/home'
    | '/inventarios/access-control'
    | '/inventarios/autorizados'
    | '/inventarios/dashboard'
    | '/site/produtos'
    | '/site/servicos'
    | '/treinamentos/alunos'
    | '/treinamentos/certificados'
    | '/treinamentos/cursos'
    | '/treinamentos/instrutores'
    | '/treinamentos/provas'
    | '/treinamentos/turmas'
    | '/usuarios/perfis'
    | '/clientes'
    | '/inventarios'
    | '/treinamentos'
    | '/usuarios'
    | '/inventarios/areas/$areaId'
    | '/inventarios/areas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/loja'
    | '/sobre'
    | '/building'
    | '/home'
    | '/inventarios/access-control'
    | '/inventarios/autorizados'
    | '/inventarios/dashboard'
    | '/site/produtos'
    | '/site/servicos'
    | '/treinamentos/alunos'
    | '/treinamentos/certificados'
    | '/treinamentos/cursos'
    | '/treinamentos/instrutores'
    | '/treinamentos/provas'
    | '/treinamentos/turmas'
    | '/usuarios/perfis'
    | '/clientes'
    | '/inventarios'
    | '/treinamentos'
    | '/usuarios'
    | '/inventarios/areas/$areaId'
    | '/inventarios/areas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/loja'
    | '/sobre'
    | '/_authenticated/building'
    | '/_authenticated/home'
    | '/_authenticated/inventarios/access-control'
    | '/_authenticated/inventarios/autorizados'
    | '/_authenticated/inventarios/dashboard'
    | '/_authenticated/site/produtos'
    | '/_authenticated/site/servicos'
    | '/_authenticated/treinamentos/alunos'
    | '/_authenticated/treinamentos/certificados'
    | '/_authenticated/treinamentos/cursos'
    | '/_authenticated/treinamentos/instrutores'
    | '/_authenticated/treinamentos/provas'
    | '/_authenticated/treinamentos/turmas'
    | '/_authenticated/usuarios/perfis'
    | '/_authenticated/clientes/'
    | '/_authenticated/inventarios/'
    | '/_authenticated/treinamentos/'
    | '/_authenticated/usuarios/'
    | '/_authenticated/inventarios/areas/$areaId'
    | '/_authenticated/inventarios/areas/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  SobreRoute: typeof SobreRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  SobreRoute: SobreRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login",
        "/loja",
        "/sobre"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/building",
        "/_authenticated/home",
        "/_authenticated/inventarios/access-control",
        "/_authenticated/inventarios/autorizados",
        "/_authenticated/inventarios/dashboard",
        "/_authenticated/site/produtos",
        "/_authenticated/site/servicos",
        "/_authenticated/treinamentos/alunos",
        "/_authenticated/treinamentos/certificados",
        "/_authenticated/treinamentos/cursos",
        "/_authenticated/treinamentos/instrutores",
        "/_authenticated/treinamentos/provas",
        "/_authenticated/treinamentos/turmas",
        "/_authenticated/usuarios/perfis",
        "/_authenticated/clientes/",
        "/_authenticated/inventarios/",
        "/_authenticated/treinamentos/",
        "/_authenticated/usuarios/",
        "/_authenticated/inventarios/areas/$areaId",
        "/_authenticated/inventarios/areas/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/loja": {
      "filePath": "loja.tsx"
    },
    "/sobre": {
      "filePath": "sobre.tsx"
    },
    "/_authenticated/building": {
      "filePath": "_authenticated/building.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/home": {
      "filePath": "_authenticated/home.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/access-control": {
      "filePath": "_authenticated/inventarios/access-control.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/autorizados": {
      "filePath": "_authenticated/inventarios/autorizados.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/dashboard": {
      "filePath": "_authenticated/inventarios/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/site/produtos": {
      "filePath": "_authenticated/site/produtos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/site/servicos": {
      "filePath": "_authenticated/site/servicos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/alunos": {
      "filePath": "_authenticated/treinamentos/alunos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/certificados": {
      "filePath": "_authenticated/treinamentos/certificados.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/cursos": {
      "filePath": "_authenticated/treinamentos/cursos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/instrutores": {
      "filePath": "_authenticated/treinamentos/instrutores.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/provas": {
      "filePath": "_authenticated/treinamentos/provas.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/turmas": {
      "filePath": "_authenticated/treinamentos/turmas.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/usuarios/perfis": {
      "filePath": "_authenticated/usuarios/perfis.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/clientes/": {
      "filePath": "_authenticated/clientes/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/": {
      "filePath": "_authenticated/inventarios/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/": {
      "filePath": "_authenticated/treinamentos/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/usuarios/": {
      "filePath": "_authenticated/usuarios/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/areas/$areaId": {
      "filePath": "_authenticated/inventarios/areas/$areaId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/areas/": {
      "filePath": "_authenticated/inventarios/areas/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
