/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/_index'
import { Route as StudentRouteImport } from './pages/student'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as StudentIndexRouteImport } from './pages/student/index'
import { Route as IndexIndexRouteImport } from './pages/_index/index'
import { Route as StudentProfileRouteImport } from './pages/student/profile'
import { Route as StudentCoursesRouteImport } from './pages/student/courses'
import { Route as AuthenticatedHomeRouteImport } from './pages/_authenticated/home'
import { Route as AuthenticatedBuildingRouteImport } from './pages/_authenticated/building'
import { Route as IndexCertificadosIndexRouteImport } from './pages/_index/certificados/index'
import { Route as AuthenticatedTreinamentosIndexRouteImport } from './pages/_authenticated/treinamentos/index'
import { Route as AuthenticatedInventariosIndexRouteImport } from './pages/_authenticated/inventarios/index'
import { Route as AuthenticatedIntegracoesIndexRouteImport } from './pages/_authenticated/integracoes/index'
import { Route as AuthenticatedEmpresaIndexRouteImport } from './pages/_authenticated/empresa/index'
import { Route as AuthenticatedClientesIndexRouteImport } from './pages/_authenticated/clientes/index'
import { Route as IndexProvaClassIdRouteImport } from './pages/_index/prova.$classId'
import { Route as IndexCertificadosIdRouteImport } from './pages/_index/certificados/$id'
import { Route as AuthenticatedInventariosDashboardRouteImport } from './pages/_authenticated/inventarios/dashboard'
import { Route as AuthenticatedInventariosAutorizadosRouteImport } from './pages/_authenticated/inventarios/autorizados'
import { Route as AuthenticatedInventariosAccessControlRouteImport } from './pages/_authenticated/inventarios/access-control'
import { Route as AuthenticatedUsuariosUsuariosIndexRouteImport } from './pages/_authenticated/usuarios/_usuarios/index'
import { Route as AuthenticatedTreinamentosAulasOnlineIndexRouteImport } from './pages/_authenticated/treinamentos/aulas-online/index'
import { Route as AuthenticatedInventariosAreasIndexRouteImport } from './pages/_authenticated/inventarios/areas/index'
import { Route as IndexCertificadosNomeIdRouteImport } from './pages/_index/certificados/$nome.$id'
import { Route as IndexAuthStudentLoginRouteImport } from './pages/_index/auth/student/login'
import { Route as AuthenticatedUsuariosPerfisPerfisRouteImport } from './pages/_authenticated/usuarios/_perfis/perfis'
import { Route as AuthenticatedTreinamentosAulasOnlineIdRouteImport } from './pages/_authenticated/treinamentos/aulas-online/$id'
import { Route as AuthenticatedTreinamentosTurmasTurmasRouteImport } from './pages/_authenticated/treinamentos/_turmas/turmas'
import { Route as AuthenticatedTreinamentosInstrutoresInstrutoresRouteImport } from './pages/_authenticated/treinamentos/_instrutores/instrutores'
import { Route as AuthenticatedTreinamentosInscricoesInscricoesRouteImport } from './pages/_authenticated/treinamentos/_inscricoes/inscricoes'
import { Route as AuthenticatedTreinamentosCursosCursosRouteImport } from './pages/_authenticated/treinamentos/_cursos/cursos'
import { Route as AuthenticatedTreinamentosCursosOnlineCursosOnlineRouteImport } from './pages/_authenticated/treinamentos/_cursos-online/cursos-online'
import { Route as AuthenticatedTreinamentosCertificadosCertificadosRouteImport } from './pages/_authenticated/treinamentos/_certificados/certificados'
import { Route as AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRouteImport } from './pages/_authenticated/treinamentos/_certificados-modelos/certificados-modelos'
import { Route as AuthenticatedTreinamentosAlunosAlunosRouteImport } from './pages/_authenticated/treinamentos/_alunos/alunos'
import { Route as AuthenticatedSiteServicosServicosRouteImport } from './pages/_authenticated/site/_servicos/servicos'
import { Route as AuthenticatedSiteProdutosProdutosRouteImport } from './pages/_authenticated/site/_produtos/produtos'
import { Route as AuthenticatedInventariosAreasAreaIdRouteImport } from './pages/_authenticated/inventarios/areas/$areaId'

const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const IndexIndexRoute = IndexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuildingRoute = AuthenticatedBuildingRouteImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const IndexCertificadosIndexRoute = IndexCertificadosIndexRouteImport.update({
  id: '/certificados/',
  path: '/certificados/',
  getParentRoute: () => IndexRoute,
} as any)
const AuthenticatedTreinamentosIndexRoute =
  AuthenticatedTreinamentosIndexRouteImport.update({
    id: '/treinamentos/',
    path: '/treinamentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventariosIndexRoute =
  AuthenticatedInventariosIndexRouteImport.update({
    id: '/inventarios/',
    path: '/inventarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegracoesIndexRoute =
  AuthenticatedIntegracoesIndexRouteImport.update({
    id: '/integracoes/',
    path: '/integracoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresaIndexRoute =
  AuthenticatedEmpresaIndexRouteImport.update({
    id: '/empresa/',
    path: '/empresa/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const IndexProvaClassIdRoute = IndexProvaClassIdRouteImport.update({
  id: '/prova/$classId',
  path: '/prova/$classId',
  getParentRoute: () => IndexRoute,
} as any)
const IndexCertificadosIdRoute = IndexCertificadosIdRouteImport.update({
  id: '/certificados/$id',
  path: '/certificados/$id',
  getParentRoute: () => IndexRoute,
} as any)
const AuthenticatedInventariosDashboardRoute =
  AuthenticatedInventariosDashboardRouteImport.update({
    id: '/inventarios/dashboard',
    path: '/inventarios/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventariosAutorizadosRoute =
  AuthenticatedInventariosAutorizadosRouteImport.update({
    id: '/inventarios/autorizados',
    path: '/inventarios/autorizados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventariosAccessControlRoute =
  AuthenticatedInventariosAccessControlRouteImport.update({
    id: '/inventarios/access-control',
    path: '/inventarios/access-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosUsuariosIndexRoute =
  AuthenticatedUsuariosUsuariosIndexRouteImport.update({
    id: '/usuarios/_usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosAulasOnlineIndexRoute =
  AuthenticatedTreinamentosAulasOnlineIndexRouteImport.update({
    id: '/treinamentos/aulas-online/',
    path: '/treinamentos/aulas-online/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventariosAreasIndexRoute =
  AuthenticatedInventariosAreasIndexRouteImport.update({
    id: '/inventarios/areas/',
    path: '/inventarios/areas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const IndexCertificadosNomeIdRoute = IndexCertificadosNomeIdRouteImport.update({
  id: '/certificados/$nome/$id',
  path: '/certificados/$nome/$id',
  getParentRoute: () => IndexRoute,
} as any)
const IndexAuthStudentLoginRoute = IndexAuthStudentLoginRouteImport.update({
  id: '/auth/student/login',
  path: '/auth/student/login',
  getParentRoute: () => IndexRoute,
} as any)
const AuthenticatedUsuariosPerfisPerfisRoute =
  AuthenticatedUsuariosPerfisPerfisRouteImport.update({
    id: '/usuarios/_perfis/perfis',
    path: '/usuarios/perfis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosAulasOnlineIdRoute =
  AuthenticatedTreinamentosAulasOnlineIdRouteImport.update({
    id: '/treinamentos/aulas-online/$id',
    path: '/treinamentos/aulas-online/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosTurmasTurmasRoute =
  AuthenticatedTreinamentosTurmasTurmasRouteImport.update({
    id: '/treinamentos/_turmas/turmas',
    path: '/treinamentos/turmas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosInstrutoresInstrutoresRoute =
  AuthenticatedTreinamentosInstrutoresInstrutoresRouteImport.update({
    id: '/treinamentos/_instrutores/instrutores',
    path: '/treinamentos/instrutores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosInscricoesInscricoesRoute =
  AuthenticatedTreinamentosInscricoesInscricoesRouteImport.update({
    id: '/treinamentos/_inscricoes/inscricoes',
    path: '/treinamentos/inscricoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosCursosCursosRoute =
  AuthenticatedTreinamentosCursosCursosRouteImport.update({
    id: '/treinamentos/_cursos/cursos',
    path: '/treinamentos/cursos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute =
  AuthenticatedTreinamentosCursosOnlineCursosOnlineRouteImport.update({
    id: '/treinamentos/_cursos-online/cursos-online',
    path: '/treinamentos/cursos-online',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosCertificadosCertificadosRoute =
  AuthenticatedTreinamentosCertificadosCertificadosRouteImport.update({
    id: '/treinamentos/_certificados/certificados',
    path: '/treinamentos/certificados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute =
  AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRouteImport.update(
    {
      id: '/treinamentos/_certificados-modelos/certificados-modelos',
      path: '/treinamentos/certificados-modelos',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedTreinamentosAlunosAlunosRoute =
  AuthenticatedTreinamentosAlunosAlunosRouteImport.update({
    id: '/treinamentos/_alunos/alunos',
    path: '/treinamentos/alunos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSiteServicosServicosRoute =
  AuthenticatedSiteServicosServicosRouteImport.update({
    id: '/site/_servicos/servicos',
    path: '/site/servicos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSiteProdutosProdutosRoute =
  AuthenticatedSiteProdutosProdutosRouteImport.update({
    id: '/site/_produtos/produtos',
    path: '/site/produtos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventariosAreasAreaIdRoute =
  AuthenticatedInventariosAreasAreaIdRouteImport.update({
    id: '/inventarios/areas/$areaId',
    path: '/inventarios/areas/$areaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/student': typeof StudentRouteWithChildren
  '/building': typeof AuthenticatedBuildingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/profile': typeof StudentProfileRoute
  '/': typeof IndexIndexRoute
  '/student/': typeof StudentIndexRoute
  '/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/certificados/$id': typeof IndexCertificadosIdRoute
  '/prova/$classId': typeof IndexProvaClassIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/empresa': typeof AuthenticatedEmpresaIndexRoute
  '/integracoes': typeof AuthenticatedIntegracoesIndexRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
  '/treinamentos': typeof AuthenticatedTreinamentosIndexRoute
  '/certificados': typeof IndexCertificadosIndexRoute
  '/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/site/produtos': typeof AuthenticatedSiteProdutosProdutosRoute
  '/site/servicos': typeof AuthenticatedSiteServicosServicosRoute
  '/treinamentos/alunos': typeof AuthenticatedTreinamentosAlunosAlunosRoute
  '/treinamentos/certificados-modelos': typeof AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute
  '/treinamentos/certificados': typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  '/treinamentos/cursos-online': typeof AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute
  '/treinamentos/cursos': typeof AuthenticatedTreinamentosCursosCursosRoute
  '/treinamentos/inscricoes': typeof AuthenticatedTreinamentosInscricoesInscricoesRoute
  '/treinamentos/instrutores': typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  '/treinamentos/turmas': typeof AuthenticatedTreinamentosTurmasTurmasRoute
  '/treinamentos/aulas-online/$id': typeof AuthenticatedTreinamentosAulasOnlineIdRoute
  '/usuarios/perfis': typeof AuthenticatedUsuariosPerfisPerfisRoute
  '/auth/student/login': typeof IndexAuthStudentLoginRoute
  '/certificados/$nome/$id': typeof IndexCertificadosNomeIdRoute
  '/inventarios/areas': typeof AuthenticatedInventariosAreasIndexRoute
  '/treinamentos/aulas-online': typeof AuthenticatedTreinamentosAulasOnlineIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/building': typeof AuthenticatedBuildingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/profile': typeof StudentProfileRoute
  '/': typeof IndexIndexRoute
  '/student': typeof StudentIndexRoute
  '/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/certificados/$id': typeof IndexCertificadosIdRoute
  '/prova/$classId': typeof IndexProvaClassIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/empresa': typeof AuthenticatedEmpresaIndexRoute
  '/integracoes': typeof AuthenticatedIntegracoesIndexRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
  '/treinamentos': typeof AuthenticatedTreinamentosIndexRoute
  '/certificados': typeof IndexCertificadosIndexRoute
  '/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/site/produtos': typeof AuthenticatedSiteProdutosProdutosRoute
  '/site/servicos': typeof AuthenticatedSiteServicosServicosRoute
  '/treinamentos/alunos': typeof AuthenticatedTreinamentosAlunosAlunosRoute
  '/treinamentos/certificados-modelos': typeof AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute
  '/treinamentos/certificados': typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  '/treinamentos/cursos-online': typeof AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute
  '/treinamentos/cursos': typeof AuthenticatedTreinamentosCursosCursosRoute
  '/treinamentos/inscricoes': typeof AuthenticatedTreinamentosInscricoesInscricoesRoute
  '/treinamentos/instrutores': typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  '/treinamentos/turmas': typeof AuthenticatedTreinamentosTurmasTurmasRoute
  '/treinamentos/aulas-online/$id': typeof AuthenticatedTreinamentosAulasOnlineIdRoute
  '/usuarios/perfis': typeof AuthenticatedUsuariosPerfisPerfisRoute
  '/auth/student/login': typeof IndexAuthStudentLoginRoute
  '/certificados/$nome/$id': typeof IndexCertificadosNomeIdRoute
  '/inventarios/areas': typeof AuthenticatedInventariosAreasIndexRoute
  '/treinamentos/aulas-online': typeof AuthenticatedTreinamentosAulasOnlineIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_index': typeof IndexRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/_authenticated/building': typeof AuthenticatedBuildingRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/profile': typeof StudentProfileRoute
  '/_index/': typeof IndexIndexRoute
  '/student/': typeof StudentIndexRoute
  '/_authenticated/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/_authenticated/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/_authenticated/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/_index/certificados/$id': typeof IndexCertificadosIdRoute
  '/_index/prova/$classId': typeof IndexProvaClassIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/empresa/': typeof AuthenticatedEmpresaIndexRoute
  '/_authenticated/integracoes/': typeof AuthenticatedIntegracoesIndexRoute
  '/_authenticated/inventarios/': typeof AuthenticatedInventariosIndexRoute
  '/_authenticated/treinamentos/': typeof AuthenticatedTreinamentosIndexRoute
  '/_index/certificados/': typeof IndexCertificadosIndexRoute
  '/_authenticated/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/_authenticated/site/_produtos/produtos': typeof AuthenticatedSiteProdutosProdutosRoute
  '/_authenticated/site/_servicos/servicos': typeof AuthenticatedSiteServicosServicosRoute
  '/_authenticated/treinamentos/_alunos/alunos': typeof AuthenticatedTreinamentosAlunosAlunosRoute
  '/_authenticated/treinamentos/_certificados-modelos/certificados-modelos': typeof AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute
  '/_authenticated/treinamentos/_certificados/certificados': typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  '/_authenticated/treinamentos/_cursos-online/cursos-online': typeof AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute
  '/_authenticated/treinamentos/_cursos/cursos': typeof AuthenticatedTreinamentosCursosCursosRoute
  '/_authenticated/treinamentos/_inscricoes/inscricoes': typeof AuthenticatedTreinamentosInscricoesInscricoesRoute
  '/_authenticated/treinamentos/_instrutores/instrutores': typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  '/_authenticated/treinamentos/_turmas/turmas': typeof AuthenticatedTreinamentosTurmasTurmasRoute
  '/_authenticated/treinamentos/aulas-online/$id': typeof AuthenticatedTreinamentosAulasOnlineIdRoute
  '/_authenticated/usuarios/_perfis/perfis': typeof AuthenticatedUsuariosPerfisPerfisRoute
  '/_index/auth/student/login': typeof IndexAuthStudentLoginRoute
  '/_index/certificados/$nome/$id': typeof IndexCertificadosNomeIdRoute
  '/_authenticated/inventarios/areas/': typeof AuthenticatedInventariosAreasIndexRoute
  '/_authenticated/treinamentos/aulas-online/': typeof AuthenticatedTreinamentosAulasOnlineIndexRoute
  '/_authenticated/usuarios/_usuarios/': typeof AuthenticatedUsuariosUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/student'
    | '/building'
    | '/home'
    | '/student/courses'
    | '/student/profile'
    | '/'
    | '/student/'
    | '/inventarios/access-control'
    | '/inventarios/autorizados'
    | '/inventarios/dashboard'
    | '/certificados/$id'
    | '/prova/$classId'
    | '/clientes'
    | '/empresa'
    | '/integracoes'
    | '/inventarios'
    | '/treinamentos'
    | '/certificados'
    | '/inventarios/areas/$areaId'
    | '/site/produtos'
    | '/site/servicos'
    | '/treinamentos/alunos'
    | '/treinamentos/certificados-modelos'
    | '/treinamentos/certificados'
    | '/treinamentos/cursos-online'
    | '/treinamentos/cursos'
    | '/treinamentos/inscricoes'
    | '/treinamentos/instrutores'
    | '/treinamentos/turmas'
    | '/treinamentos/aulas-online/$id'
    | '/usuarios/perfis'
    | '/auth/student/login'
    | '/certificados/$nome/$id'
    | '/inventarios/areas'
    | '/treinamentos/aulas-online'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/building'
    | '/home'
    | '/student/courses'
    | '/student/profile'
    | '/'
    | '/student'
    | '/inventarios/access-control'
    | '/inventarios/autorizados'
    | '/inventarios/dashboard'
    | '/certificados/$id'
    | '/prova/$classId'
    | '/clientes'
    | '/empresa'
    | '/integracoes'
    | '/inventarios'
    | '/treinamentos'
    | '/certificados'
    | '/inventarios/areas/$areaId'
    | '/site/produtos'
    | '/site/servicos'
    | '/treinamentos/alunos'
    | '/treinamentos/certificados-modelos'
    | '/treinamentos/certificados'
    | '/treinamentos/cursos-online'
    | '/treinamentos/cursos'
    | '/treinamentos/inscricoes'
    | '/treinamentos/instrutores'
    | '/treinamentos/turmas'
    | '/treinamentos/aulas-online/$id'
    | '/usuarios/perfis'
    | '/auth/student/login'
    | '/certificados/$nome/$id'
    | '/inventarios/areas'
    | '/treinamentos/aulas-online'
    | '/usuarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_index'
    | '/student'
    | '/_authenticated/building'
    | '/_authenticated/home'
    | '/student/courses'
    | '/student/profile'
    | '/_index/'
    | '/student/'
    | '/_authenticated/inventarios/access-control'
    | '/_authenticated/inventarios/autorizados'
    | '/_authenticated/inventarios/dashboard'
    | '/_index/certificados/$id'
    | '/_index/prova/$classId'
    | '/_authenticated/clientes/'
    | '/_authenticated/empresa/'
    | '/_authenticated/integracoes/'
    | '/_authenticated/inventarios/'
    | '/_authenticated/treinamentos/'
    | '/_index/certificados/'
    | '/_authenticated/inventarios/areas/$areaId'
    | '/_authenticated/site/_produtos/produtos'
    | '/_authenticated/site/_servicos/servicos'
    | '/_authenticated/treinamentos/_alunos/alunos'
    | '/_authenticated/treinamentos/_certificados-modelos/certificados-modelos'
    | '/_authenticated/treinamentos/_certificados/certificados'
    | '/_authenticated/treinamentos/_cursos-online/cursos-online'
    | '/_authenticated/treinamentos/_cursos/cursos'
    | '/_authenticated/treinamentos/_inscricoes/inscricoes'
    | '/_authenticated/treinamentos/_instrutores/instrutores'
    | '/_authenticated/treinamentos/_turmas/turmas'
    | '/_authenticated/treinamentos/aulas-online/$id'
    | '/_authenticated/usuarios/_perfis/perfis'
    | '/_index/auth/student/login'
    | '/_index/certificados/$nome/$id'
    | '/_authenticated/inventarios/areas/'
    | '/_authenticated/treinamentos/aulas-online/'
    | '/_authenticated/usuarios/_usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  IndexRoute: typeof IndexRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexRouteImport
      parentRoute: typeof IndexRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/building': {
      id: '/_authenticated/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof AuthenticatedBuildingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_index/certificados/': {
      id: '/_index/certificados/'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof IndexCertificadosIndexRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_authenticated/treinamentos/': {
      id: '/_authenticated/treinamentos/'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof AuthenticatedTreinamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventarios/': {
      id: '/_authenticated/inventarios/'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof AuthenticatedInventariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes/': {
      id: '/_authenticated/integracoes/'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresa/': {
      id: '/_authenticated/empresa/'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_index/prova/$classId': {
      id: '/_index/prova/$classId'
      path: '/prova/$classId'
      fullPath: '/prova/$classId'
      preLoaderRoute: typeof IndexProvaClassIdRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_index/certificados/$id': {
      id: '/_index/certificados/$id'
      path: '/certificados/$id'
      fullPath: '/certificados/$id'
      preLoaderRoute: typeof IndexCertificadosIdRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_authenticated/inventarios/dashboard': {
      id: '/_authenticated/inventarios/dashboard'
      path: '/inventarios/dashboard'
      fullPath: '/inventarios/dashboard'
      preLoaderRoute: typeof AuthenticatedInventariosDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventarios/autorizados': {
      id: '/_authenticated/inventarios/autorizados'
      path: '/inventarios/autorizados'
      fullPath: '/inventarios/autorizados'
      preLoaderRoute: typeof AuthenticatedInventariosAutorizadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventarios/access-control': {
      id: '/_authenticated/inventarios/access-control'
      path: '/inventarios/access-control'
      fullPath: '/inventarios/access-control'
      preLoaderRoute: typeof AuthenticatedInventariosAccessControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios/_usuarios/': {
      id: '/_authenticated/usuarios/_usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/aulas-online/': {
      id: '/_authenticated/treinamentos/aulas-online/'
      path: '/treinamentos/aulas-online'
      fullPath: '/treinamentos/aulas-online'
      preLoaderRoute: typeof AuthenticatedTreinamentosAulasOnlineIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventarios/areas/': {
      id: '/_authenticated/inventarios/areas/'
      path: '/inventarios/areas'
      fullPath: '/inventarios/areas'
      preLoaderRoute: typeof AuthenticatedInventariosAreasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_index/certificados/$nome/$id': {
      id: '/_index/certificados/$nome/$id'
      path: '/certificados/$nome/$id'
      fullPath: '/certificados/$nome/$id'
      preLoaderRoute: typeof IndexCertificadosNomeIdRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_index/auth/student/login': {
      id: '/_index/auth/student/login'
      path: '/auth/student/login'
      fullPath: '/auth/student/login'
      preLoaderRoute: typeof IndexAuthStudentLoginRouteImport
      parentRoute: typeof IndexRoute
    }
    '/_authenticated/usuarios/_perfis/perfis': {
      id: '/_authenticated/usuarios/_perfis/perfis'
      path: '/usuarios/perfis'
      fullPath: '/usuarios/perfis'
      preLoaderRoute: typeof AuthenticatedUsuariosPerfisPerfisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/aulas-online/$id': {
      id: '/_authenticated/treinamentos/aulas-online/$id'
      path: '/treinamentos/aulas-online/$id'
      fullPath: '/treinamentos/aulas-online/$id'
      preLoaderRoute: typeof AuthenticatedTreinamentosAulasOnlineIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_turmas/turmas': {
      id: '/_authenticated/treinamentos/_turmas/turmas'
      path: '/treinamentos/turmas'
      fullPath: '/treinamentos/turmas'
      preLoaderRoute: typeof AuthenticatedTreinamentosTurmasTurmasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_instrutores/instrutores': {
      id: '/_authenticated/treinamentos/_instrutores/instrutores'
      path: '/treinamentos/instrutores'
      fullPath: '/treinamentos/instrutores'
      preLoaderRoute: typeof AuthenticatedTreinamentosInstrutoresInstrutoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_inscricoes/inscricoes': {
      id: '/_authenticated/treinamentos/_inscricoes/inscricoes'
      path: '/treinamentos/inscricoes'
      fullPath: '/treinamentos/inscricoes'
      preLoaderRoute: typeof AuthenticatedTreinamentosInscricoesInscricoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_cursos/cursos': {
      id: '/_authenticated/treinamentos/_cursos/cursos'
      path: '/treinamentos/cursos'
      fullPath: '/treinamentos/cursos'
      preLoaderRoute: typeof AuthenticatedTreinamentosCursosCursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_cursos-online/cursos-online': {
      id: '/_authenticated/treinamentos/_cursos-online/cursos-online'
      path: '/treinamentos/cursos-online'
      fullPath: '/treinamentos/cursos-online'
      preLoaderRoute: typeof AuthenticatedTreinamentosCursosOnlineCursosOnlineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_certificados/certificados': {
      id: '/_authenticated/treinamentos/_certificados/certificados'
      path: '/treinamentos/certificados'
      fullPath: '/treinamentos/certificados'
      preLoaderRoute: typeof AuthenticatedTreinamentosCertificadosCertificadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_certificados-modelos/certificados-modelos': {
      id: '/_authenticated/treinamentos/_certificados-modelos/certificados-modelos'
      path: '/treinamentos/certificados-modelos'
      fullPath: '/treinamentos/certificados-modelos'
      preLoaderRoute: typeof AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treinamentos/_alunos/alunos': {
      id: '/_authenticated/treinamentos/_alunos/alunos'
      path: '/treinamentos/alunos'
      fullPath: '/treinamentos/alunos'
      preLoaderRoute: typeof AuthenticatedTreinamentosAlunosAlunosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/site/_servicos/servicos': {
      id: '/_authenticated/site/_servicos/servicos'
      path: '/site/servicos'
      fullPath: '/site/servicos'
      preLoaderRoute: typeof AuthenticatedSiteServicosServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/site/_produtos/produtos': {
      id: '/_authenticated/site/_produtos/produtos'
      path: '/site/produtos'
      fullPath: '/site/produtos'
      preLoaderRoute: typeof AuthenticatedSiteProdutosProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventarios/areas/$areaId': {
      id: '/_authenticated/inventarios/areas/$areaId'
      path: '/inventarios/areas/$areaId'
      fullPath: '/inventarios/areas/$areaId'
      preLoaderRoute: typeof AuthenticatedInventariosAreasAreaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBuildingRoute: typeof AuthenticatedBuildingRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInventariosAccessControlRoute: typeof AuthenticatedInventariosAccessControlRoute
  AuthenticatedInventariosAutorizadosRoute: typeof AuthenticatedInventariosAutorizadosRoute
  AuthenticatedInventariosDashboardRoute: typeof AuthenticatedInventariosDashboardRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedEmpresaIndexRoute: typeof AuthenticatedEmpresaIndexRoute
  AuthenticatedIntegracoesIndexRoute: typeof AuthenticatedIntegracoesIndexRoute
  AuthenticatedInventariosIndexRoute: typeof AuthenticatedInventariosIndexRoute
  AuthenticatedTreinamentosIndexRoute: typeof AuthenticatedTreinamentosIndexRoute
  AuthenticatedInventariosAreasAreaIdRoute: typeof AuthenticatedInventariosAreasAreaIdRoute
  AuthenticatedSiteProdutosProdutosRoute: typeof AuthenticatedSiteProdutosProdutosRoute
  AuthenticatedSiteServicosServicosRoute: typeof AuthenticatedSiteServicosServicosRoute
  AuthenticatedTreinamentosAlunosAlunosRoute: typeof AuthenticatedTreinamentosAlunosAlunosRoute
  AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute: typeof AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute
  AuthenticatedTreinamentosCertificadosCertificadosRoute: typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute: typeof AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute
  AuthenticatedTreinamentosCursosCursosRoute: typeof AuthenticatedTreinamentosCursosCursosRoute
  AuthenticatedTreinamentosInscricoesInscricoesRoute: typeof AuthenticatedTreinamentosInscricoesInscricoesRoute
  AuthenticatedTreinamentosInstrutoresInstrutoresRoute: typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  AuthenticatedTreinamentosTurmasTurmasRoute: typeof AuthenticatedTreinamentosTurmasTurmasRoute
  AuthenticatedTreinamentosAulasOnlineIdRoute: typeof AuthenticatedTreinamentosAulasOnlineIdRoute
  AuthenticatedUsuariosPerfisPerfisRoute: typeof AuthenticatedUsuariosPerfisPerfisRoute
  AuthenticatedInventariosAreasIndexRoute: typeof AuthenticatedInventariosAreasIndexRoute
  AuthenticatedTreinamentosAulasOnlineIndexRoute: typeof AuthenticatedTreinamentosAulasOnlineIndexRoute
  AuthenticatedUsuariosUsuariosIndexRoute: typeof AuthenticatedUsuariosUsuariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuildingRoute: AuthenticatedBuildingRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInventariosAccessControlRoute:
    AuthenticatedInventariosAccessControlRoute,
  AuthenticatedInventariosAutorizadosRoute:
    AuthenticatedInventariosAutorizadosRoute,
  AuthenticatedInventariosDashboardRoute:
    AuthenticatedInventariosDashboardRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedEmpresaIndexRoute: AuthenticatedEmpresaIndexRoute,
  AuthenticatedIntegracoesIndexRoute: AuthenticatedIntegracoesIndexRoute,
  AuthenticatedInventariosIndexRoute: AuthenticatedInventariosIndexRoute,
  AuthenticatedTreinamentosIndexRoute: AuthenticatedTreinamentosIndexRoute,
  AuthenticatedInventariosAreasAreaIdRoute:
    AuthenticatedInventariosAreasAreaIdRoute,
  AuthenticatedSiteProdutosProdutosRoute:
    AuthenticatedSiteProdutosProdutosRoute,
  AuthenticatedSiteServicosServicosRoute:
    AuthenticatedSiteServicosServicosRoute,
  AuthenticatedTreinamentosAlunosAlunosRoute:
    AuthenticatedTreinamentosAlunosAlunosRoute,
  AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute:
    AuthenticatedTreinamentosCertificadosModelosCertificadosModelosRoute,
  AuthenticatedTreinamentosCertificadosCertificadosRoute:
    AuthenticatedTreinamentosCertificadosCertificadosRoute,
  AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute:
    AuthenticatedTreinamentosCursosOnlineCursosOnlineRoute,
  AuthenticatedTreinamentosCursosCursosRoute:
    AuthenticatedTreinamentosCursosCursosRoute,
  AuthenticatedTreinamentosInscricoesInscricoesRoute:
    AuthenticatedTreinamentosInscricoesInscricoesRoute,
  AuthenticatedTreinamentosInstrutoresInstrutoresRoute:
    AuthenticatedTreinamentosInstrutoresInstrutoresRoute,
  AuthenticatedTreinamentosTurmasTurmasRoute:
    AuthenticatedTreinamentosTurmasTurmasRoute,
  AuthenticatedTreinamentosAulasOnlineIdRoute:
    AuthenticatedTreinamentosAulasOnlineIdRoute,
  AuthenticatedUsuariosPerfisPerfisRoute:
    AuthenticatedUsuariosPerfisPerfisRoute,
  AuthenticatedInventariosAreasIndexRoute:
    AuthenticatedInventariosAreasIndexRoute,
  AuthenticatedTreinamentosAulasOnlineIndexRoute:
    AuthenticatedTreinamentosAulasOnlineIndexRoute,
  AuthenticatedUsuariosUsuariosIndexRoute:
    AuthenticatedUsuariosUsuariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface IndexRouteChildren {
  IndexIndexRoute: typeof IndexIndexRoute
  IndexCertificadosIdRoute: typeof IndexCertificadosIdRoute
  IndexProvaClassIdRoute: typeof IndexProvaClassIdRoute
  IndexCertificadosIndexRoute: typeof IndexCertificadosIndexRoute
  IndexAuthStudentLoginRoute: typeof IndexAuthStudentLoginRoute
  IndexCertificadosNomeIdRoute: typeof IndexCertificadosNomeIdRoute
}

const IndexRouteChildren: IndexRouteChildren = {
  IndexIndexRoute: IndexIndexRoute,
  IndexCertificadosIdRoute: IndexCertificadosIdRoute,
  IndexProvaClassIdRoute: IndexProvaClassIdRoute,
  IndexCertificadosIndexRoute: IndexCertificadosIndexRoute,
  IndexAuthStudentLoginRoute: IndexAuthStudentLoginRoute,
  IndexCertificadosNomeIdRoute: IndexCertificadosNomeIdRoute,
}

const IndexRouteWithChildren = IndexRoute._addFileChildren(IndexRouteChildren)

interface StudentRouteChildren {
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCoursesRoute: StudentCoursesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  IndexRoute: IndexRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
