/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as AuthenticatedImport } from './pages/_authenticated'
import { Route as IndexIndexImport } from './pages/_index/index'
import { Route as IndexTreinamentoImport } from './pages/_index/treinamento'
import { Route as IndexSobreImport } from './pages/_index/sobre'
import { Route as IndexLojaImport } from './pages/_index/loja'
import { Route as IndexLoginImport } from './pages/_index/login'
import { Route as AuthenticatedHomeImport } from './pages/_authenticated/home'
import { Route as AuthenticatedBuildingImport } from './pages/_authenticated/building'
import { Route as IndexCertificadosIndexImport } from './pages/_index/certificados/index'
import { Route as AuthenticatedTreinamentosIndexImport } from './pages/_authenticated/treinamentos/index'
import { Route as AuthenticatedInventariosIndexImport } from './pages/_authenticated/inventarios/index'
import { Route as AuthenticatedClientesIndexImport } from './pages/_authenticated/clientes/index'
import { Route as IndexTurmaIdImport } from './pages/_index/turma.$id'
import { Route as IndexProvaClassIdImport } from './pages/_index/prova.$classId'
import { Route as IndexCertificadosIdImport } from './pages/_index/certificados/$id'
import { Route as AuthenticatedTreinamentosProvasImport } from './pages/_authenticated/treinamentos/provas'
import { Route as AuthenticatedInventariosDashboardImport } from './pages/_authenticated/inventarios/dashboard'
import { Route as AuthenticatedInventariosAutorizadosImport } from './pages/_authenticated/inventarios/autorizados'
import { Route as AuthenticatedInventariosAccessControlImport } from './pages/_authenticated/inventarios/access-control'
import { Route as AuthenticatedUsuariosUsuariosIndexImport } from './pages/_authenticated/usuarios/_usuarios/index'
import { Route as AuthenticatedInventariosAreasIndexImport } from './pages/_authenticated/inventarios/areas/index'
import { Route as AuthenticatedUsuariosPerfisPerfisImport } from './pages/_authenticated/usuarios/_perfis/perfis'
import { Route as AuthenticatedTreinamentosTurmasTurmasImport } from './pages/_authenticated/treinamentos/_turmas/turmas'
import { Route as AuthenticatedTreinamentosInstrutoresInstrutoresImport } from './pages/_authenticated/treinamentos/_instrutores/instrutores'
import { Route as AuthenticatedTreinamentosCursosCursosImport } from './pages/_authenticated/treinamentos/_cursos/cursos'
import { Route as AuthenticatedTreinamentosCertificadosCertificadosImport } from './pages/_authenticated/treinamentos/_certificados/certificados'
import { Route as AuthenticatedTreinamentosAlunosAlunosImport } from './pages/_authenticated/treinamentos/_alunos/alunos'
import { Route as AuthenticatedSiteServicosServicosImport } from './pages/_authenticated/site/_servicos/servicos'
import { Route as AuthenticatedSiteProdutosProdutosImport } from './pages/_authenticated/site/_produtos/produtos'
import { Route as AuthenticatedInventariosAreasAreaIdImport } from './pages/_authenticated/inventarios/areas/$areaId'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  id: '/_index/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IndexTreinamentoRoute = IndexTreinamentoImport.update({
  id: '/_index/treinamento',
  path: '/treinamento',
  getParentRoute: () => rootRoute,
} as any)

const IndexSobreRoute = IndexSobreImport.update({
  id: '/_index/sobre',
  path: '/sobre',
  getParentRoute: () => rootRoute,
} as any)

const IndexLojaRoute = IndexLojaImport.update({
  id: '/_index/loja',
  path: '/loja',
  getParentRoute: () => rootRoute,
} as any)

const IndexLoginRoute = IndexLoginImport.update({
  id: '/_index/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeRoute = AuthenticatedHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedBuildingRoute = AuthenticatedBuildingImport.update({
  id: '/building',
  path: '/building',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const IndexCertificadosIndexRoute = IndexCertificadosIndexImport.update({
  id: '/_index/certificados/',
  path: '/certificados/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTreinamentosIndexRoute =
  AuthenticatedTreinamentosIndexImport.update({
    id: '/treinamentos/',
    path: '/treinamentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosIndexRoute =
  AuthenticatedInventariosIndexImport.update({
    id: '/inventarios/',
    path: '/inventarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedClientesIndexRoute = AuthenticatedClientesIndexImport.update(
  {
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const IndexTurmaIdRoute = IndexTurmaIdImport.update({
  id: '/_index/turma/$id',
  path: '/turma/$id',
  getParentRoute: () => rootRoute,
} as any)

const IndexProvaClassIdRoute = IndexProvaClassIdImport.update({
  id: '/_index/prova/$classId',
  path: '/prova/$classId',
  getParentRoute: () => rootRoute,
} as any)

const IndexCertificadosIdRoute = IndexCertificadosIdImport.update({
  id: '/_index/certificados/$id',
  path: '/certificados/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTreinamentosProvasRoute =
  AuthenticatedTreinamentosProvasImport.update({
    id: '/treinamentos/provas',
    path: '/treinamentos/provas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosDashboardRoute =
  AuthenticatedInventariosDashboardImport.update({
    id: '/inventarios/dashboard',
    path: '/inventarios/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAutorizadosRoute =
  AuthenticatedInventariosAutorizadosImport.update({
    id: '/inventarios/autorizados',
    path: '/inventarios/autorizados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAccessControlRoute =
  AuthenticatedInventariosAccessControlImport.update({
    id: '/inventarios/access-control',
    path: '/inventarios/access-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedUsuariosUsuariosIndexRoute =
  AuthenticatedUsuariosUsuariosIndexImport.update({
    id: '/usuarios/_usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAreasIndexRoute =
  AuthenticatedInventariosAreasIndexImport.update({
    id: '/inventarios/areas/',
    path: '/inventarios/areas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedUsuariosPerfisPerfisRoute =
  AuthenticatedUsuariosPerfisPerfisImport.update({
    id: '/usuarios/_perfis/perfis',
    path: '/usuarios/perfis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosTurmasTurmasRoute =
  AuthenticatedTreinamentosTurmasTurmasImport.update({
    id: '/treinamentos/_turmas/turmas',
    path: '/treinamentos/turmas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosInstrutoresInstrutoresRoute =
  AuthenticatedTreinamentosInstrutoresInstrutoresImport.update({
    id: '/treinamentos/_instrutores/instrutores',
    path: '/treinamentos/instrutores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosCursosCursosRoute =
  AuthenticatedTreinamentosCursosCursosImport.update({
    id: '/treinamentos/_cursos/cursos',
    path: '/treinamentos/cursos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosCertificadosCertificadosRoute =
  AuthenticatedTreinamentosCertificadosCertificadosImport.update({
    id: '/treinamentos/_certificados/certificados',
    path: '/treinamentos/certificados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedTreinamentosAlunosAlunosRoute =
  AuthenticatedTreinamentosAlunosAlunosImport.update({
    id: '/treinamentos/_alunos/alunos',
    path: '/treinamentos/alunos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSiteServicosServicosRoute =
  AuthenticatedSiteServicosServicosImport.update({
    id: '/site/_servicos/servicos',
    path: '/site/servicos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSiteProdutosProdutosRoute =
  AuthenticatedSiteProdutosProdutosImport.update({
    id: '/site/_produtos/produtos',
    path: '/site/produtos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInventariosAreasAreaIdRoute =
  AuthenticatedInventariosAreasAreaIdImport.update({
    id: '/inventarios/areas/$areaId',
    path: '/inventarios/areas/$areaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/building': {
      id: '/_authenticated/building'
      path: '/building'
      fullPath: '/building'
      preLoaderRoute: typeof AuthenticatedBuildingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_index/login': {
      id: '/_index/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof IndexLoginImport
      parentRoute: typeof rootRoute
    }
    '/_index/loja': {
      id: '/_index/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof IndexLojaImport
      parentRoute: typeof rootRoute
    }
    '/_index/sobre': {
      id: '/_index/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof IndexSobreImport
      parentRoute: typeof rootRoute
    }
    '/_index/treinamento': {
      id: '/_index/treinamento'
      path: '/treinamento'
      fullPath: '/treinamento'
      preLoaderRoute: typeof IndexTreinamentoImport
      parentRoute: typeof rootRoute
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/inventarios/access-control': {
      id: '/_authenticated/inventarios/access-control'
      path: '/inventarios/access-control'
      fullPath: '/inventarios/access-control'
      preLoaderRoute: typeof AuthenticatedInventariosAccessControlImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/autorizados': {
      id: '/_authenticated/inventarios/autorizados'
      path: '/inventarios/autorizados'
      fullPath: '/inventarios/autorizados'
      preLoaderRoute: typeof AuthenticatedInventariosAutorizadosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/dashboard': {
      id: '/_authenticated/inventarios/dashboard'
      path: '/inventarios/dashboard'
      fullPath: '/inventarios/dashboard'
      preLoaderRoute: typeof AuthenticatedInventariosDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/provas': {
      id: '/_authenticated/treinamentos/provas'
      path: '/treinamentos/provas'
      fullPath: '/treinamentos/provas'
      preLoaderRoute: typeof AuthenticatedTreinamentosProvasImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_index/certificados/$id': {
      id: '/_index/certificados/$id'
      path: '/certificados/$id'
      fullPath: '/certificados/$id'
      preLoaderRoute: typeof IndexCertificadosIdImport
      parentRoute: typeof rootRoute
    }
    '/_index/prova/$classId': {
      id: '/_index/prova/$classId'
      path: '/prova/$classId'
      fullPath: '/prova/$classId'
      preLoaderRoute: typeof IndexProvaClassIdImport
      parentRoute: typeof rootRoute
    }
    '/_index/turma/$id': {
      id: '/_index/turma/$id'
      path: '/turma/$id'
      fullPath: '/turma/$id'
      preLoaderRoute: typeof IndexTurmaIdImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/': {
      id: '/_authenticated/inventarios/'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof AuthenticatedInventariosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/': {
      id: '/_authenticated/treinamentos/'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof AuthenticatedTreinamentosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_index/certificados/': {
      id: '/_index/certificados/'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof IndexCertificadosIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/inventarios/areas/$areaId': {
      id: '/_authenticated/inventarios/areas/$areaId'
      path: '/inventarios/areas/$areaId'
      fullPath: '/inventarios/areas/$areaId'
      preLoaderRoute: typeof AuthenticatedInventariosAreasAreaIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/site/_produtos/produtos': {
      id: '/_authenticated/site/_produtos/produtos'
      path: '/site/produtos'
      fullPath: '/site/produtos'
      preLoaderRoute: typeof AuthenticatedSiteProdutosProdutosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/site/_servicos/servicos': {
      id: '/_authenticated/site/_servicos/servicos'
      path: '/site/servicos'
      fullPath: '/site/servicos'
      preLoaderRoute: typeof AuthenticatedSiteServicosServicosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/_alunos/alunos': {
      id: '/_authenticated/treinamentos/_alunos/alunos'
      path: '/treinamentos/alunos'
      fullPath: '/treinamentos/alunos'
      preLoaderRoute: typeof AuthenticatedTreinamentosAlunosAlunosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/_certificados/certificados': {
      id: '/_authenticated/treinamentos/_certificados/certificados'
      path: '/treinamentos/certificados'
      fullPath: '/treinamentos/certificados'
      preLoaderRoute: typeof AuthenticatedTreinamentosCertificadosCertificadosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/_cursos/cursos': {
      id: '/_authenticated/treinamentos/_cursos/cursos'
      path: '/treinamentos/cursos'
      fullPath: '/treinamentos/cursos'
      preLoaderRoute: typeof AuthenticatedTreinamentosCursosCursosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/_instrutores/instrutores': {
      id: '/_authenticated/treinamentos/_instrutores/instrutores'
      path: '/treinamentos/instrutores'
      fullPath: '/treinamentos/instrutores'
      preLoaderRoute: typeof AuthenticatedTreinamentosInstrutoresInstrutoresImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/treinamentos/_turmas/turmas': {
      id: '/_authenticated/treinamentos/_turmas/turmas'
      path: '/treinamentos/turmas'
      fullPath: '/treinamentos/turmas'
      preLoaderRoute: typeof AuthenticatedTreinamentosTurmasTurmasImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/usuarios/_perfis/perfis': {
      id: '/_authenticated/usuarios/_perfis/perfis'
      path: '/usuarios/perfis'
      fullPath: '/usuarios/perfis'
      preLoaderRoute: typeof AuthenticatedUsuariosPerfisPerfisImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/inventarios/areas/': {
      id: '/_authenticated/inventarios/areas/'
      path: '/inventarios/areas'
      fullPath: '/inventarios/areas'
      preLoaderRoute: typeof AuthenticatedInventariosAreasIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/usuarios/_usuarios/': {
      id: '/_authenticated/usuarios/_usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosUsuariosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedBuildingRoute: typeof AuthenticatedBuildingRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInventariosAccessControlRoute: typeof AuthenticatedInventariosAccessControlRoute
  AuthenticatedInventariosAutorizadosRoute: typeof AuthenticatedInventariosAutorizadosRoute
  AuthenticatedInventariosDashboardRoute: typeof AuthenticatedInventariosDashboardRoute
  AuthenticatedTreinamentosProvasRoute: typeof AuthenticatedTreinamentosProvasRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedInventariosIndexRoute: typeof AuthenticatedInventariosIndexRoute
  AuthenticatedTreinamentosIndexRoute: typeof AuthenticatedTreinamentosIndexRoute
  AuthenticatedInventariosAreasAreaIdRoute: typeof AuthenticatedInventariosAreasAreaIdRoute
  AuthenticatedSiteProdutosProdutosRoute: typeof AuthenticatedSiteProdutosProdutosRoute
  AuthenticatedSiteServicosServicosRoute: typeof AuthenticatedSiteServicosServicosRoute
  AuthenticatedTreinamentosAlunosAlunosRoute: typeof AuthenticatedTreinamentosAlunosAlunosRoute
  AuthenticatedTreinamentosCertificadosCertificadosRoute: typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  AuthenticatedTreinamentosCursosCursosRoute: typeof AuthenticatedTreinamentosCursosCursosRoute
  AuthenticatedTreinamentosInstrutoresInstrutoresRoute: typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  AuthenticatedTreinamentosTurmasTurmasRoute: typeof AuthenticatedTreinamentosTurmasTurmasRoute
  AuthenticatedUsuariosPerfisPerfisRoute: typeof AuthenticatedUsuariosPerfisPerfisRoute
  AuthenticatedInventariosAreasIndexRoute: typeof AuthenticatedInventariosAreasIndexRoute
  AuthenticatedUsuariosUsuariosIndexRoute: typeof AuthenticatedUsuariosUsuariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBuildingRoute: AuthenticatedBuildingRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInventariosAccessControlRoute:
    AuthenticatedInventariosAccessControlRoute,
  AuthenticatedInventariosAutorizadosRoute:
    AuthenticatedInventariosAutorizadosRoute,
  AuthenticatedInventariosDashboardRoute:
    AuthenticatedInventariosDashboardRoute,
  AuthenticatedTreinamentosProvasRoute: AuthenticatedTreinamentosProvasRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedInventariosIndexRoute: AuthenticatedInventariosIndexRoute,
  AuthenticatedTreinamentosIndexRoute: AuthenticatedTreinamentosIndexRoute,
  AuthenticatedInventariosAreasAreaIdRoute:
    AuthenticatedInventariosAreasAreaIdRoute,
  AuthenticatedSiteProdutosProdutosRoute:
    AuthenticatedSiteProdutosProdutosRoute,
  AuthenticatedSiteServicosServicosRoute:
    AuthenticatedSiteServicosServicosRoute,
  AuthenticatedTreinamentosAlunosAlunosRoute:
    AuthenticatedTreinamentosAlunosAlunosRoute,
  AuthenticatedTreinamentosCertificadosCertificadosRoute:
    AuthenticatedTreinamentosCertificadosCertificadosRoute,
  AuthenticatedTreinamentosCursosCursosRoute:
    AuthenticatedTreinamentosCursosCursosRoute,
  AuthenticatedTreinamentosInstrutoresInstrutoresRoute:
    AuthenticatedTreinamentosInstrutoresInstrutoresRoute,
  AuthenticatedTreinamentosTurmasTurmasRoute:
    AuthenticatedTreinamentosTurmasTurmasRoute,
  AuthenticatedUsuariosPerfisPerfisRoute:
    AuthenticatedUsuariosPerfisPerfisRoute,
  AuthenticatedInventariosAreasIndexRoute:
    AuthenticatedInventariosAreasIndexRoute,
  AuthenticatedUsuariosUsuariosIndexRoute:
    AuthenticatedUsuariosUsuariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/building': typeof AuthenticatedBuildingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/login': typeof IndexLoginRoute
  '/loja': typeof IndexLojaRoute
  '/sobre': typeof IndexSobreRoute
  '/treinamento': typeof IndexTreinamentoRoute
  '/': typeof IndexIndexRoute
  '/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/treinamentos/provas': typeof AuthenticatedTreinamentosProvasRoute
  '/certificados/$id': typeof IndexCertificadosIdRoute
  '/prova/$classId': typeof IndexProvaClassIdRoute
  '/turma/$id': typeof IndexTurmaIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
  '/treinamentos': typeof AuthenticatedTreinamentosIndexRoute
  '/certificados': typeof IndexCertificadosIndexRoute
  '/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/site/produtos': typeof AuthenticatedSiteProdutosProdutosRoute
  '/site/servicos': typeof AuthenticatedSiteServicosServicosRoute
  '/treinamentos/alunos': typeof AuthenticatedTreinamentosAlunosAlunosRoute
  '/treinamentos/certificados': typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  '/treinamentos/cursos': typeof AuthenticatedTreinamentosCursosCursosRoute
  '/treinamentos/instrutores': typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  '/treinamentos/turmas': typeof AuthenticatedTreinamentosTurmasTurmasRoute
  '/usuarios/perfis': typeof AuthenticatedUsuariosPerfisPerfisRoute
  '/inventarios/areas': typeof AuthenticatedInventariosAreasIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosUsuariosIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/building': typeof AuthenticatedBuildingRoute
  '/home': typeof AuthenticatedHomeRoute
  '/login': typeof IndexLoginRoute
  '/loja': typeof IndexLojaRoute
  '/sobre': typeof IndexSobreRoute
  '/treinamento': typeof IndexTreinamentoRoute
  '/': typeof IndexIndexRoute
  '/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/treinamentos/provas': typeof AuthenticatedTreinamentosProvasRoute
  '/certificados/$id': typeof IndexCertificadosIdRoute
  '/prova/$classId': typeof IndexProvaClassIdRoute
  '/turma/$id': typeof IndexTurmaIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
  '/treinamentos': typeof AuthenticatedTreinamentosIndexRoute
  '/certificados': typeof IndexCertificadosIndexRoute
  '/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/site/produtos': typeof AuthenticatedSiteProdutosProdutosRoute
  '/site/servicos': typeof AuthenticatedSiteServicosServicosRoute
  '/treinamentos/alunos': typeof AuthenticatedTreinamentosAlunosAlunosRoute
  '/treinamentos/certificados': typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  '/treinamentos/cursos': typeof AuthenticatedTreinamentosCursosCursosRoute
  '/treinamentos/instrutores': typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  '/treinamentos/turmas': typeof AuthenticatedTreinamentosTurmasTurmasRoute
  '/usuarios/perfis': typeof AuthenticatedUsuariosPerfisPerfisRoute
  '/inventarios/areas': typeof AuthenticatedInventariosAreasIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosUsuariosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/building': typeof AuthenticatedBuildingRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_index/login': typeof IndexLoginRoute
  '/_index/loja': typeof IndexLojaRoute
  '/_index/sobre': typeof IndexSobreRoute
  '/_index/treinamento': typeof IndexTreinamentoRoute
  '/_index/': typeof IndexIndexRoute
  '/_authenticated/inventarios/access-control': typeof AuthenticatedInventariosAccessControlRoute
  '/_authenticated/inventarios/autorizados': typeof AuthenticatedInventariosAutorizadosRoute
  '/_authenticated/inventarios/dashboard': typeof AuthenticatedInventariosDashboardRoute
  '/_authenticated/treinamentos/provas': typeof AuthenticatedTreinamentosProvasRoute
  '/_index/certificados/$id': typeof IndexCertificadosIdRoute
  '/_index/prova/$classId': typeof IndexProvaClassIdRoute
  '/_index/turma/$id': typeof IndexTurmaIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/inventarios/': typeof AuthenticatedInventariosIndexRoute
  '/_authenticated/treinamentos/': typeof AuthenticatedTreinamentosIndexRoute
  '/_index/certificados/': typeof IndexCertificadosIndexRoute
  '/_authenticated/inventarios/areas/$areaId': typeof AuthenticatedInventariosAreasAreaIdRoute
  '/_authenticated/site/_produtos/produtos': typeof AuthenticatedSiteProdutosProdutosRoute
  '/_authenticated/site/_servicos/servicos': typeof AuthenticatedSiteServicosServicosRoute
  '/_authenticated/treinamentos/_alunos/alunos': typeof AuthenticatedTreinamentosAlunosAlunosRoute
  '/_authenticated/treinamentos/_certificados/certificados': typeof AuthenticatedTreinamentosCertificadosCertificadosRoute
  '/_authenticated/treinamentos/_cursos/cursos': typeof AuthenticatedTreinamentosCursosCursosRoute
  '/_authenticated/treinamentos/_instrutores/instrutores': typeof AuthenticatedTreinamentosInstrutoresInstrutoresRoute
  '/_authenticated/treinamentos/_turmas/turmas': typeof AuthenticatedTreinamentosTurmasTurmasRoute
  '/_authenticated/usuarios/_perfis/perfis': typeof AuthenticatedUsuariosPerfisPerfisRoute
  '/_authenticated/inventarios/areas/': typeof AuthenticatedInventariosAreasIndexRoute
  '/_authenticated/usuarios/_usuarios/': typeof AuthenticatedUsuariosUsuariosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/building'
    | '/home'
    | '/login'
    | '/loja'
    | '/sobre'
    | '/treinamento'
    | '/'
    | '/inventarios/access-control'
    | '/inventarios/autorizados'
    | '/inventarios/dashboard'
    | '/treinamentos/provas'
    | '/certificados/$id'
    | '/prova/$classId'
    | '/turma/$id'
    | '/clientes'
    | '/inventarios'
    | '/treinamentos'
    | '/certificados'
    | '/inventarios/areas/$areaId'
    | '/site/produtos'
    | '/site/servicos'
    | '/treinamentos/alunos'
    | '/treinamentos/certificados'
    | '/treinamentos/cursos'
    | '/treinamentos/instrutores'
    | '/treinamentos/turmas'
    | '/usuarios/perfis'
    | '/inventarios/areas'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/building'
    | '/home'
    | '/login'
    | '/loja'
    | '/sobre'
    | '/treinamento'
    | '/'
    | '/inventarios/access-control'
    | '/inventarios/autorizados'
    | '/inventarios/dashboard'
    | '/treinamentos/provas'
    | '/certificados/$id'
    | '/prova/$classId'
    | '/turma/$id'
    | '/clientes'
    | '/inventarios'
    | '/treinamentos'
    | '/certificados'
    | '/inventarios/areas/$areaId'
    | '/site/produtos'
    | '/site/servicos'
    | '/treinamentos/alunos'
    | '/treinamentos/certificados'
    | '/treinamentos/cursos'
    | '/treinamentos/instrutores'
    | '/treinamentos/turmas'
    | '/usuarios/perfis'
    | '/inventarios/areas'
    | '/usuarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/building'
    | '/_authenticated/home'
    | '/_index/login'
    | '/_index/loja'
    | '/_index/sobre'
    | '/_index/treinamento'
    | '/_index/'
    | '/_authenticated/inventarios/access-control'
    | '/_authenticated/inventarios/autorizados'
    | '/_authenticated/inventarios/dashboard'
    | '/_authenticated/treinamentos/provas'
    | '/_index/certificados/$id'
    | '/_index/prova/$classId'
    | '/_index/turma/$id'
    | '/_authenticated/clientes/'
    | '/_authenticated/inventarios/'
    | '/_authenticated/treinamentos/'
    | '/_index/certificados/'
    | '/_authenticated/inventarios/areas/$areaId'
    | '/_authenticated/site/_produtos/produtos'
    | '/_authenticated/site/_servicos/servicos'
    | '/_authenticated/treinamentos/_alunos/alunos'
    | '/_authenticated/treinamentos/_certificados/certificados'
    | '/_authenticated/treinamentos/_cursos/cursos'
    | '/_authenticated/treinamentos/_instrutores/instrutores'
    | '/_authenticated/treinamentos/_turmas/turmas'
    | '/_authenticated/usuarios/_perfis/perfis'
    | '/_authenticated/inventarios/areas/'
    | '/_authenticated/usuarios/_usuarios/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  IndexLoginRoute: typeof IndexLoginRoute
  IndexLojaRoute: typeof IndexLojaRoute
  IndexSobreRoute: typeof IndexSobreRoute
  IndexTreinamentoRoute: typeof IndexTreinamentoRoute
  IndexIndexRoute: typeof IndexIndexRoute
  IndexCertificadosIdRoute: typeof IndexCertificadosIdRoute
  IndexProvaClassIdRoute: typeof IndexProvaClassIdRoute
  IndexTurmaIdRoute: typeof IndexTurmaIdRoute
  IndexCertificadosIndexRoute: typeof IndexCertificadosIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  IndexLoginRoute: IndexLoginRoute,
  IndexLojaRoute: IndexLojaRoute,
  IndexSobreRoute: IndexSobreRoute,
  IndexTreinamentoRoute: IndexTreinamentoRoute,
  IndexIndexRoute: IndexIndexRoute,
  IndexCertificadosIdRoute: IndexCertificadosIdRoute,
  IndexProvaClassIdRoute: IndexProvaClassIdRoute,
  IndexTurmaIdRoute: IndexTurmaIdRoute,
  IndexCertificadosIndexRoute: IndexCertificadosIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_index/login",
        "/_index/loja",
        "/_index/sobre",
        "/_index/treinamento",
        "/_index/",
        "/_index/certificados/$id",
        "/_index/prova/$classId",
        "/_index/turma/$id",
        "/_index/certificados/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/building",
        "/_authenticated/home",
        "/_authenticated/inventarios/access-control",
        "/_authenticated/inventarios/autorizados",
        "/_authenticated/inventarios/dashboard",
        "/_authenticated/treinamentos/provas",
        "/_authenticated/clientes/",
        "/_authenticated/inventarios/",
        "/_authenticated/treinamentos/",
        "/_authenticated/inventarios/areas/$areaId",
        "/_authenticated/site/_produtos/produtos",
        "/_authenticated/site/_servicos/servicos",
        "/_authenticated/treinamentos/_alunos/alunos",
        "/_authenticated/treinamentos/_certificados/certificados",
        "/_authenticated/treinamentos/_cursos/cursos",
        "/_authenticated/treinamentos/_instrutores/instrutores",
        "/_authenticated/treinamentos/_turmas/turmas",
        "/_authenticated/usuarios/_perfis/perfis",
        "/_authenticated/inventarios/areas/",
        "/_authenticated/usuarios/_usuarios/"
      ]
    },
    "/_authenticated/building": {
      "filePath": "_authenticated/building.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/home": {
      "filePath": "_authenticated/home.tsx",
      "parent": "/_authenticated"
    },
    "/_index/login": {
      "filePath": "_index/login.tsx"
    },
    "/_index/loja": {
      "filePath": "_index/loja.tsx"
    },
    "/_index/sobre": {
      "filePath": "_index/sobre.tsx"
    },
    "/_index/treinamento": {
      "filePath": "_index/treinamento.tsx"
    },
    "/_index/": {
      "filePath": "_index/index.tsx"
    },
    "/_authenticated/inventarios/access-control": {
      "filePath": "_authenticated/inventarios/access-control.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/autorizados": {
      "filePath": "_authenticated/inventarios/autorizados.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/dashboard": {
      "filePath": "_authenticated/inventarios/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/provas": {
      "filePath": "_authenticated/treinamentos/provas.tsx",
      "parent": "/_authenticated"
    },
    "/_index/certificados/$id": {
      "filePath": "_index/certificados/$id.tsx"
    },
    "/_index/prova/$classId": {
      "filePath": "_index/prova.$classId.tsx"
    },
    "/_index/turma/$id": {
      "filePath": "_index/turma.$id.tsx"
    },
    "/_authenticated/clientes/": {
      "filePath": "_authenticated/clientes/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/": {
      "filePath": "_authenticated/inventarios/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/": {
      "filePath": "_authenticated/treinamentos/index.tsx",
      "parent": "/_authenticated"
    },
    "/_index/certificados/": {
      "filePath": "_index/certificados/index.tsx"
    },
    "/_authenticated/inventarios/areas/$areaId": {
      "filePath": "_authenticated/inventarios/areas/$areaId.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/site/_produtos/produtos": {
      "filePath": "_authenticated/site/_produtos/produtos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/site/_servicos/servicos": {
      "filePath": "_authenticated/site/_servicos/servicos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/_alunos/alunos": {
      "filePath": "_authenticated/treinamentos/_alunos/alunos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/_certificados/certificados": {
      "filePath": "_authenticated/treinamentos/_certificados/certificados.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/_cursos/cursos": {
      "filePath": "_authenticated/treinamentos/_cursos/cursos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/_instrutores/instrutores": {
      "filePath": "_authenticated/treinamentos/_instrutores/instrutores.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/treinamentos/_turmas/turmas": {
      "filePath": "_authenticated/treinamentos/_turmas/turmas.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/usuarios/_perfis/perfis": {
      "filePath": "_authenticated/usuarios/_perfis/perfis.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventarios/areas/": {
      "filePath": "_authenticated/inventarios/areas/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/usuarios/_usuarios/": {
      "filePath": "_authenticated/usuarios/_usuarios/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
